### ISSUE TITLE
I get the following when tryign to build.

### ISSUE THREAD

**Issue by lfmunoz** [Gnurou/kdev-kernel#10]
CMake Error at /usr/share/kde4/apps/cmake/modules/FindKDE4Internal.cmake:1267 (message):
  ERROR: the installed kdelibs version 4.4.5 is too old, at least version
  4.7.0 is required

I raelly can't upgrade to kdelibs 4.7.0 or greater since I am using  debian and I have the lastest stable (squeeze) which has kde version 4.4.5. Is there any way I can build this so it works with kdelibs 4.4.5?

**Comment by Gnurou** [comment]
I'm afraid not - kdev-kernel uses very bleeding-edge code of KDevelop, so you need to comply to these requirements. Furthermore I am currently doing a major rework of the whole thing - you might want to wait a little bit before trying it out.
