### ISSUE TITLE
Defconfig list don't contains in subdir defconfig

### ISSUE THREAD

**Issue by condo4** [Gnurou/kdev-kernel#11]
For platform PowerPC, in config directory, we have subfolder and config like:
44x/yosemite_defconfig

I wrote a patch to start to don't add folder in the widget list, and to add subfolder item.

diff --git a/kdevkernelconfigwidget.cpp b/kdevkernelconfigwidget.cpp
index 54aed9e..f6596ac 100644
--- a/kdevkernelconfigwidget.cpp
+++ b/kdevkernelconfigwidget.cpp
@@ -128,8 +128,20 @@ void KDevKernelConfigWidget::archChanged (const QString &arch)
     KUrl pRoot(_projectRoot);
     pRoot.adjustPath(KUrl::AddTrailingSlash);
     QDir configDirs(KUrl(pRoot, QString("arch/%1/configs").arg(arch)).toLocalFile());
-    foreach (const QString &configFile, configDirs.entryList()) {
-    foreach (const QString &configFile, configDirs.entryList(QDir::Files)) {
       if (configFile.startsWith('.')) continue;
  +
       defconfig->addItem(configFile.left(configFile.size() - QString("_defconfig").size()));
   }
-    foreach (const QString &configFile, configDirs.entryList(QDir::Dirs)) {
-        if (configFile.startsWith('.')) continue;
-        QDir configSubDirs(KUrl(pRoot, QString("arch/%1/configs/%2").arg(arch).arg(configFile)).toLocalFile());
-        foreach (const QString &configSubFile, configSubDirs.entryList(QDir::Files)) {
-            if (configSubFile.startsWith('.')) continue;
-            QString defconf = configFile + "/" + configSubFile;
-            defconfig->addItem(defconf.left(defconf.size() - QString("_defconfig").size()));
-        }
  +
  +
-    }
  }

**Comment by Gnurou** [comment]
Hi, thanks for the patch but the auto-formatting ruined it and I cannot figure it out. Could you submit a pull request instead?

**Comment by condo4** [comment]
Pull request submit in #12
