### ISSUE TITLE
cmake_minimum_required not set

### ISSUE THREAD

**Issue by sangorrin** [Gnurou/kdev-kernel#18]
Bonjour,

In Debian Jessie, cmake complains that the minimum version is not set:

Adding
        + cmake_minimum_required(VERSION 3.0)
to CMakeLists.txt worked.

Thanks,
Daniel

PS: Jessie comes with Kdevelop 4.7 so I thought I wouldn't have to recompile it. However, it seems to me that it's not working because when I open a project I cannot select Linux Kernel in the [Build system] drop-down menu.

**Comment by Gnurou** [comment]
Hey, sorry for the delayed reply.

KDevelop 5.0 actually makes much is this plugin obsolete, so I suggest switching to it. I will try to re-start a new version of the plugin for it in order to make configuration easier. So for the moment, I will just close this issue.
