### ISSUE TITLE
Is the project going to work along KDevelop5 or is it dead?

### ISSUE THREAD

**Issue by Petross404** [Gnurou/kdev-kernel#21]
Is kdev-kernel abandoned or should we hope it will revive again?

**Comment by Gnurou** [comment]
It would need a complete port (understand: rewrite) to KDevelop 5. Note that KDevelop 5 itself has gotten much, much better for kernel editing, such that now kdev-kernel would just be a project manager to tell it which files to parse and which macros to define.

I don't consider it abandoned yet, but as time is scarce contributions are of course welcome! :)
