### ISSUE TITLE
include/linux/list.h does not parse

### ISSUE THREAD

**Issue by Gnurou** [Gnurou/kdev-kernel#6]
Plenty of largely used functions are unavailable because of this.

**Comment by Gnurou** [comment]
That's because of the use of the new keyword. KDevelop's parser needs to be adapted to support parsing C-only files.

**Comment by Gnurou** [comment]
"new", "delete", "class", "virtual", ... need to be ignored when parsing pure C files.

**Comment by intelfx** [comment]
As a temporary workaround, one can add defines like
new -> c_new
delete -> c_delete
class ->c_class
and so on... Maybe you add them?

BTW, do you have not-merged-upstream "language features" support in your kdevelop fork?

**Comment by Gnurou** [comment]
I think this is fixed now actually - closing that issue.

The language features branch is not merged yet because the base architecture it introduces to handle differences between C and C++ has been rejected - and by the meantime I got more and more convinced that this parser is not worth maintaining when more powerful and exact alternatives exist. My main work is not on the CLang branch for which I have some early results - feel free to help if you want better kernel parsing. :)

https://github.com/Gnurou/kdevelop/tree/clang

**Comment by intelfx** [comment]
Hm, clang is exactly what I was thinking of last week :) I'll definitely try to help you if I have some spare time.

**Comment by Gnurou** [comment]
Hey, that would be great :) So far I have proper variable handling (including jump to declaration/definition) with the little amount of code I committed, and it really seems like we could get something functional rather quickly if someone with a better understanding of KDevelop's internals were to join. Let's discuss that more deeply if you have the will and resources to help.

**Comment by intelfx** [comment]
I highly doubt that my KDevelop knowledge is better than yours... ;) But anyway, will is present, and resources are to be found.
